#include "opengl.h"

#include <SDL.h>

namespace mw {

#if MW_OPENGLES2

#define FUNC_POINTER_DEF(ret,func,params) ret (KHRONOS_APIENTRY *func) params = func;
	FUNC_POINTER_DEF(void, glActiveTexture, (GLenum))
	FUNC_POINTER_DEF(void, glAttachShader, (GLuint, GLuint))
	FUNC_POINTER_DEF(void, glBindAttribLocation, (GLuint, GLuint, const char *))
	FUNC_POINTER_DEF(void, glBindTexture, (GLenum, GLuint))
	FUNC_POINTER_DEF(void, glBlendFunc, (GLenum, GLenum))
	FUNC_POINTER_DEF(void, glBlendFuncSeparate, (GLenum, GLenum, GLenum, GLenum))
	FUNC_POINTER_DEF(void, glClear, (GLbitfield))
	FUNC_POINTER_DEF(void, glClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
	FUNC_POINTER_DEF(void, glCompileShader, (GLuint))
	FUNC_POINTER_DEF(GLuint, glCreateProgram, (void))
	FUNC_POINTER_DEF(GLuint, glCreateShader, (GLenum))
	FUNC_POINTER_DEF(void, glDeleteProgram, (GLuint))
	FUNC_POINTER_DEF(void, glDeleteShader, (GLuint))
	FUNC_POINTER_DEF(void, glDeleteTextures, (GLsizei, const GLuint *))
	FUNC_POINTER_DEF(void, glDisable, (GLenum))
	FUNC_POINTER_DEF(void, glDisableVertexAttribArray, (GLuint))
	FUNC_POINTER_DEF(void, glDrawArrays, (GLenum, GLint, GLsizei))
	FUNC_POINTER_DEF(void, glEnable, (GLenum))
	FUNC_POINTER_DEF(void, glEnableVertexAttribArray, (GLuint))
	FUNC_POINTER_DEF(void, glFinish, (void))
	FUNC_POINTER_DEF(void, glGenFramebuffers, (GLsizei, GLuint *))
	FUNC_POINTER_DEF(void, glGenTextures, (GLsizei, GLuint *))
	FUNC_POINTER_DEF(void, glGetBooleanv, (GLenum, GLboolean *))
	FUNC_POINTER_DEF(const GLubyte *, glGetString, (GLenum))
	FUNC_POINTER_DEF(GLenum, glGetError, (void))
	FUNC_POINTER_DEF(void, glGetIntegerv, (GLenum, GLint *))
	FUNC_POINTER_DEF(void, glGetProgramiv, (GLuint, GLenum, GLint *))
	FUNC_POINTER_DEF(void, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei *, char *))
	FUNC_POINTER_DEF(void, glGetShaderiv, (GLuint, GLenum, GLint *))
	FUNC_POINTER_DEF(GLint, glGetUniformLocation, (GLuint, const char *))
	FUNC_POINTER_DEF(void, glLinkProgram, (GLuint))
	FUNC_POINTER_DEF(void, glPixelStorei, (GLenum, GLint))
	FUNC_POINTER_DEF(void, glReadPixels, (GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid*))
	FUNC_POINTER_DEF(void, glScissor, (GLint, GLint, GLsizei, GLsizei))
	FUNC_POINTER_DEF(void, glShaderBinary, (GLsizei, const GLuint *, GLenum, const void *, GLsizei))
	FUNC_POINTER_DEF(void, glShaderSource, (GLuint, GLsizei, const char **, const GLint *))
	FUNC_POINTER_DEF(void, glTexImage2D, (GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void *))
	FUNC_POINTER_DEF(void, glTexParameteri, (GLenum, GLenum, GLint))
	FUNC_POINTER_DEF(void, glTexSubImage2D, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
	FUNC_POINTER_DEF(void, glUniform1i, (GLint, GLint))
	FUNC_POINTER_DEF(void, glUniform4f, (GLint, GLfloat, GLfloat, GLfloat, GLfloat))
	FUNC_POINTER_DEF(void, glUniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat *))
	FUNC_POINTER_DEF(void, glUseProgram, (GLuint))
	FUNC_POINTER_DEF(void, glVertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void *))
	FUNC_POINTER_DEF(void, glViewport, (GLint, GLint, GLsizei, GLsizei))
	FUNC_POINTER_DEF(void, glBindFramebuffer, (GLenum, GLuint))
	FUNC_POINTER_DEF(void, glFramebufferTexture2D, (GLenum, GLenum, GLenum, GLuint, GLint))
	FUNC_POINTER_DEF(GLenum, glCheckFramebufferStatus, (GLenum))
	FUNC_POINTER_DEF(void, glDeleteFramebuffers, (GLsizei, const GLuint *))
	FUNC_POINTER_DEF(GLint, glGetAttribLocation, (GLuint, const GLchar *))
#undef FuncPointer

#define FUNC_POINTER_LINC(ret,func,params) func = (ret (KHRONOS_APIENTRY*)params) SDL_GL_GetProcAddress(#func);
	void initGLES2() {
		FUNC_POINTER_LINC(void, glActiveTexture, (GLenum))
		FUNC_POINTER_LINC(void, glAttachShader, (GLuint, GLuint))
		FUNC_POINTER_LINC(void, glBindAttribLocation, (GLuint, GLuint, const char *))
		FUNC_POINTER_LINC(void, glBindTexture, (GLenum, GLuint))
		FUNC_POINTER_LINC(void, glBlendFunc, (GLenum, GLenum))
		FUNC_POINTER_LINC(void, glBlendFuncSeparate, (GLenum, GLenum, GLenum, GLenum))
		FUNC_POINTER_LINC(void, glClear, (GLbitfield))
		FUNC_POINTER_LINC(void, glClearColor, (GLclampf, GLclampf, GLclampf, GLclampf))
		FUNC_POINTER_LINC(void, glCompileShader, (GLuint))
		FUNC_POINTER_LINC(GLuint, glCreateProgram, (void))
		FUNC_POINTER_LINC(GLuint, glCreateShader, (GLenum))
		FUNC_POINTER_LINC(void, glDeleteProgram, (GLuint))
		FUNC_POINTER_LINC(void, glDeleteShader, (GLuint))
		FUNC_POINTER_LINC(void, glDeleteTextures, (GLsizei, const GLuint *))
		FUNC_POINTER_LINC(void, glDisable, (GLenum))
		FUNC_POINTER_LINC(void, glDisableVertexAttribArray, (GLuint))
		FUNC_POINTER_LINC(void, glDrawArrays, (GLenum, GLint, GLsizei))
		FUNC_POINTER_LINC(void, glEnable, (GLenum))
		FUNC_POINTER_LINC(void, glEnableVertexAttribArray, (GLuint))
		FUNC_POINTER_LINC(void, glFinish, (void))
		FUNC_POINTER_LINC(void, glGenFramebuffers, (GLsizei, GLuint *))
		FUNC_POINTER_LINC(void, glGenTextures, (GLsizei, GLuint *))
		FUNC_POINTER_LINC(void, glGetBooleanv, (GLenum, GLboolean *))
		FUNC_POINTER_LINC(const GLubyte *, glGetString, (GLenum))
		FUNC_POINTER_LINC(GLenum, glGetError, (void))
		FUNC_POINTER_LINC(void, glGetIntegerv, (GLenum, GLint *))
		FUNC_POINTER_LINC(void, glGetProgramiv, (GLuint, GLenum, GLint *))
		FUNC_POINTER_LINC(void, glGetShaderInfoLog, (GLuint, GLsizei, GLsizei *, char *))
		FUNC_POINTER_LINC(void, glGetShaderiv, (GLuint, GLenum, GLint *))
		FUNC_POINTER_LINC(GLint, glGetUniformLocation, (GLuint, const char *))
		FUNC_POINTER_LINC(void, glLinkProgram, (GLuint))
		FUNC_POINTER_LINC(void, glPixelStorei, (GLenum, GLint))
		FUNC_POINTER_LINC(void, glReadPixels, (GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLvoid*))
		FUNC_POINTER_LINC(void, glScissor, (GLint, GLint, GLsizei, GLsizei))
		FUNC_POINTER_LINC(void, glShaderBinary, (GLsizei, const GLuint *, GLenum, const void *, GLsizei))
		FUNC_POINTER_LINC(void, glShaderSource, (GLuint, GLsizei, const char **, const GLint *))
		FUNC_POINTER_LINC(void, glTexImage2D, (GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, const void *))
		FUNC_POINTER_LINC(void, glTexParameteri, (GLenum, GLenum, GLint))
		FUNC_POINTER_LINC(void, glTexSubImage2D, (GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, const GLvoid *))
		FUNC_POINTER_LINC(void, glUniform1i, (GLint, GLint))
		FUNC_POINTER_LINC(void, glUniform4f, (GLint, GLfloat, GLfloat, GLfloat, GLfloat))
		FUNC_POINTER_LINC(void, glUniformMatrix4fv, (GLint, GLsizei, GLboolean, const GLfloat *))
		FUNC_POINTER_LINC(void, glUseProgram, (GLuint))
		FUNC_POINTER_LINC(void, glVertexAttribPointer, (GLuint, GLint, GLenum, GLboolean, GLsizei, const void *))
		FUNC_POINTER_LINC(void, glViewport, (GLint, GLint, GLsizei, GLsizei))
		FUNC_POINTER_LINC(void, glBindFramebuffer, (GLenum, GLuint))
		FUNC_POINTER_LINC(void, glFramebufferTexture2D, (GLenum, GLenum, GLenum, GLuint, GLint))
		FUNC_POINTER_LINC(GLenum, glCheckFramebufferStatus, (GLenum))
		FUNC_POINTER_LINC(void, glDeleteFramebuffers, (GLsizei, const GLuint *))
		FUNC_POINTER_LINC(GLint, glGetAttribLocation, (GLuint, const GLchar *))
	}
#undef FUNC_POINTER_LINC

#else // MW_OPENGLES2

#endif // MW_OPENGLES2

} // Namespace mw.
